### PR TITLE
Enable batches in profile generation

### PR DESCRIPTION
**Pull request by b-remy**
With this PR, we are now able to generate Gaussian and Sersic profiles by batch. The only requirement is to provide parameters by list of floats, tensors or numpy arrays (which are then converted in TF tensors).

An example can be seen at https://github.com/b-remy/gems/blob/main/toymodel1.py ([752107e](https://github.com/b-remy/gems/commit/752107e903759d10f845e5f4be929c740ad49b11)):

Figure_2

### CODE REVIEW

**Review by EiffL — APPROVED** [review]
LGTM

**Comment by b-remy** [comment]
Hi @EiffL , I just made a few more changes in order to:
- enable `tf.function`
- fix all the NaNs appearing for some Sersic profiles

**Comment by EiffL** [comment]
It works much better :-D but I haven't tried to run a chain with free hlr and n yet

**Comment by EiffL** [comment]
hummm still running into some weird problems when trying to run a chain over size and ellipticity

**Comment by b-remy** [comment]
It should be fixed now. I ran a chain with free n and hlr and no error occurred.

**Pull request merged**
