### PR TITLE
Light profiles

### PR DESCRIPTION
**Pull request by b-remy**
This PR adds a few inputs to the light profiles such as:
- pixel scale
- non integrer Sersic index
- half-light-radius for Sersic

### CODE REVIEW

**Comment by EiffL** [comment]
It looks good :-) is it ready for review?

**Comment by b-remy** [comment]
There are still some GalSim features that are missing but which I don't need at the moment.

Otherwise the ones I added are documented and tested, so yes, ready for review!

**Comment by b-remy** [comment]
But it seems there are some conflicts, maybe it's because I forgot to do a git pull in the branch `light_profiles` after the merge of `documentation` into `master`....

**Comment by b-remy** [comment]
This is ready now :)

**Review by EiffL — APPROVED** [review]
Looks very good to me

**Pull request merged**
